# Default values for primes.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
image:
	repository: quay.io/codymccain/primes
	tag: latest
	pullPolicy: IfNotPresent
manager:
	resources:
		limits:
			cpu: 100m
			memory: 64Mi
worker:
	resources:
		limits:
			cpu: 500m
			memory: 128Mi




